			ORG 	&H000

Safe_2:  	IN      XIO           	
        	AND     Key3Mask      	
        	JPOS    Safe_2         

MANUALDETECT: IN 	SWITCHES
			STORE 	CHECK
			AND 	One
			JZERO 	AUTODETECT
			LOAD 	CHECK
			AND 	Two
			JPOS 	SETUP_R
			JUMP 	SETUP_L
        	
AUTODETECT: LOAD	EnSonar0
			OR		EnSonar5
			OUT 	SONAREN
			
			IN		DIST0			
			STORE	LEFTD
			IN		DIST5			
			SUB		LEFTD
			JPOS	SETUP_L
			JUMP	SETUP_R				
			
SETUP_R:	LOAD	One
			OUT 	LEDS
			LOAD	EnSonar3		
			OR		EnSonar5		
			OR		EnSonar4		
			OUT		SONAREN			
			
CHECK_FRONT_R: IN	DIST3
			OUT		SEVENSEG
			SUB		MINFRONTTHRESH 	
			JPOS	CHECK_CRASH_R	
			JUMP	INSIDE_TURN_R	

CHECK_CRASH_R: IN 	DIST4
			SUB 	MINCRASHTHRESH
			JPOS	CHECK_SIDE_R
			JUMP 	INSIDE_TURN_R

CHECK_SIDE_R: IN	DIST5
			OUT		LCD
			SUB		NOSIDETHRESH	
			JPOS	OUTSIDE_TURN_R	
			ADD		NOSIDETHRESH	
			SUB		MINSIDETHRESH	
			JNEG	MOVE_AWAY_R		
			ADD		MINSIDETHRESH	
			SUB		MAXSIDETHRESH	
			JPOS	MOVE_TOWARD_R	

			JUMP	MOVE_FORWARD_R	

INSIDE_TURN_R: LOAD One
			OUT 	LEDS
			LOAD	QSPEED
			OUT		LVELCMD
			LOAD	HALFSPEED
			OUT		RVELCMD			
			JUMP	CHECK_FRONT_R	

OUTSIDE_TURN_R: LOAD Two
			OUT 	LEDS
			LOAD	OSPEED
			OUT		RVELCMD
			LOAD	HALFSPEED
			OUT		LVELCMD
			JUMP	CHECK_FRONT_R		

MOVE_AWAY_R: LOAD 	Three
			OUT 	LEDS			
			LOAD	HALFSPEED
			OUT     RVELCMD
			LOAD	ASPEED
			OUT     LVELCMD
			JUMP	CHECK_FRONT_R	

MOVE_TOWARD_R: LOAD Four		
			OUT 	LEDS			
			LOAD	ASPEED
			OUT     RVELCMD
			LOAD	HALFSPEED
			OUT     LVELCMD
			JUMP	CHECK_FRONT_R	

MOVE_FORWARD_R: LOAD Five
			OUT 	LEDS
			LOAD	HALFSPEED
			OUT     RVELCMD
			OUT     LVELCMD			
			JUMP	CHECK_FRONT_R	


SETUP_L:	LOAD	Two
			OUT		LEDS
			LOAD	EnSonar0		
			OR		EnSonar1		
			OR		EnSonar2		
			OUT		SONAREN			
			
CHECK_FRONT_L: IN	DIST2
			OUT		SEVENSEG
			SUB		MINFRONTTHRESH 	
			JPOS	CHECK_CRASH_L	
			JUMP	INSIDE_TURN_L	

CHECK_CRASH_L: IN	DIST1
			SUB 	MINCRASHTHRESH
			JPOS	CHECK_SIDE_L
			JUMP 	INSIDE_TURN_L

CHECK_SIDE_L: IN	DIST0
			OUT		LCD
			SUB		NOSIDETHRESH	
			JPOS	OUTSIDE_TURN_L	
			ADD		NOSIDETHRESH	
			SUB		MINSIDETHRESH	
			JNEG	MOVE_AWAY_L		
			ADD		MINSIDETHRESH	
			SUB		MAXSIDETHRESH	
			JPOS	MOVE_TOWARD_L	

			JUMP	MOVE_FORWARD_L	

INSIDE_TURN_L: LOAD One
			OUT 	LEDS
			LOAD	QSPEED
			OUT		RVELCMD
			LOAD	HALFSPEED
			OUT		LVELCMD			
			JUMP	CHECK_FRONT_L	

OUTSIDE_TURN_L: LOAD Two
			OUT 	LEDS
			LOAD	OSPEED
			OUT		LVELCMD
			LOAD	HALFSPEED
			OUT		RVELCMD
			JUMP	CHECK_FRONT_L		

MOVE_AWAY_L: LOAD 	Three
			OUT 	LEDS			
			LOAD	HALFSPEED
			OUT     LVELCMD
			LOAD	ASPEED
			OUT     RVELCMD
			JUMP	CHECK_FRONT_L	
MOVE_TOWARD_L: LOAD Four		
			OUT 	LEDS			
			LOAD	ASPEED
			OUT     LVELCMD
			LOAD	HALFSPEED
			OUT     RVELCMD
			JUMP	CHECK_FRONT_L	

MOVE_FORWARD_L: LOAD Five
			OUT 	LEDS
			LOAD	HALFSPEED
			OUT     LVELCMD
			OUT     RVELCMD			
			JUMP	CHECK_FRONT_L	
			
Zero:        DW    0
One:         DW    1
Two:         DW    2
Three:       DW    3
Four:        DW    4
Five:        DW    5
Six:         DW    6
Seven:       DW    7
Eight:       DW    8
Nine:        DW    9
Ten:         DW    10
MAX:		 DW	   &H0FFF
EnSonar0:    DW    &B00000001
EnSonar1:    DW    &B00000010
EnSonar2:    DW    &B00000100
EnSonar3:    DW    &B00001000
EnSonar4:    DW    &B00010000
EnSonar5:    DW    &B00100000
EnSonar6:    DW    &B01000000
EnSonar7:    DW    &B10000000
RNEG:        DW    0
Key3Mask:    DW    &B00000100
Key2Mask:	 DW	   &B00000010
Key1Mask:    DW    &B00000001

FULLSPEED:   DW    &H007F
LeftVel:     DW    0
RightVel:    DW    0

HALFSPEED:   DW    &H0040
QSPEED:		 DW    &H0004
OSPEED:		 DW	   &H0004
ASPEED:		 DW	   &H0020

CHECK:		DW 0

LEFTD:		DW 0
RIGHTD:		DW 0

MINCRASHTHRESH: DW 200
MINFRONTTHRESH: DW 500
NOSIDETHRESH: DW 1000
MINSIDETHRESH: DW 200
MAXSIDETHRESH: DW 220
SWITCHES:    EQU   &H00
LEDS:        EQU   &H01
TIMER:       EQU   &H02
XIO:         EQU   &H03
SEVENSEG:    EQU   &H04
LCD:         EQU   &H06
LPOSLOW:     EQU   &H80
LPOSHIGH:    EQU   &H81
LVEL:        EQU   &H82
LVELCMD:     EQU   &H83
RPOSLOW:     EQU   &H88
RPOSHIGH:    EQU   &H89
RVEL:        EQU   &H8A
RVELCMD:     EQU   &H8B
SONAR:       EQU   &HA0  
DIST0:       EQU   &HA8  
DIST1:       EQU   &HA9  
DIST2:       EQU   &HAA  
DIST3:       EQU   &HAB  
DIST4:       EQU   &HAC  
DIST5:       EQU   &HAD  
DIST6:       EQU   &HAE  
DIST7:       EQU   &HAF  
SONAREN:     EQU   &HB2  